name: dio_response_validator
description: An extension on Dio response futures to perform validation and data transformation
version: 0.2.0
homepage: https://github.com/Rexios80/dio_response_validator

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  dio: ^4.0.6

dev_dependencies:
  rexios_lints: ^5.0.0
  test: ^1.16.0
